### ISSUE TITLE
Where does the sound file go?

### ISSUE THREAD

**Issue by Varelden** [Martyrshot/runelite-marty-entrance#1]
Title says it

**Comment by pettrs** [comment]
wondering the samething

**Comment by pettrs** [comment]
figured it out. open Run and paste in the following directory
%userprofile%\.runelite\sounds\marty\entrance

![image](https://github.com/Martyrshot/runelite-marty-walkup/assets/75093127/f34002e0-cd1b-44c0-b685-677e5d23feb3)

place the .mp3 file in there

**Comment by Martyrshot** [comment]
Hey, sorry I missed this question. It goes in `RUNELITE_DIR/sounds/marty/entrance/`

I've been meaning to fix the bug where it doesn't initialize the folder properly. 🫠

**Comment by pettrs** [comment]
also, it appears to not accept mp3 at all. converted files to .wav and it worked.

awesome plugin btw, it it possible to make this when people appear in-game too? with a cooldown.

say you're waiting at TOB bank, and someone finally shows up and the soundfile plays. maybe limited to once per x minutes, or once per login session? think something excluse to that would make the plugin more attractive. maybe also a few preset sounds in addition to the custom ones?

i personally added the "let's get ready to rumble" announcer sound when my raid buddy logs in

funny plugin btw

**Comment by Martyrshot** [comment]
> also, it appears to not accept mp3 at all. converted files to .wav and it worked.

Ah yes, I remember there being something about licensing preventing mp3s from working with the core java sound library (or something... it's been awhile since I've looked into it lol).

> awesome plugin btw, it it possible to make this when people appear in-game too? with a cooldown.
> 
> say you're waiting at TOB bank, and someone finally shows up and the soundfile plays. maybe limited to once per x minutes, or once per login session? think something excluse to that would make the plugin more attractive. maybe also a few preset sounds in addition to the custom ones?

Maybe you could set a radius of X squares. When someone on your list leaves the radius then reenters the radius the sound could play. I would have to look into the runelite API, but in principle it sounds simple enough to add. :) It might be a little while before I could give it a try though. :( 


> i personally added the "let's get ready to rumble" announcer sound when my raid buddy logs in

Haha amazing! I love it! :)

**Comment by Martyrshot** [comment]
Thanks for the issue @Varelden and @pettrs. Sorry it took so long to respond. My email gets flood with github notifications, and I guess this one slipped through the cracks. :(
